### ISSUE TITLE
Change start sound

### ISSUE THREAD

**Issue by Melt2002** [meower-media-co/Linux-Meower-launcher-client#1]
We need a temporary start sound to replace the one in the launcher at the moment, due to copyright.

**Comment by Bloctans** [comment]
hmmmm, when you do that, can you commit the start sound to the windows release?

**Comment by Melt2002** [comment]
Yes.

**Comment by Melt2002** [comment]
A new commit will be made soon to change the audio file with the sound provided in Meower. @Bloctans, I do not have the ability to make the installer, so you may need to make a new installer for the new update. Otherwise, I will close this issue now.
